### ISSUE TITLE
Manejo de traducciones

### ISSUE THREAD

**Issue by iambrosi** [PHPmvd/phpday-website#16]
Hay dos opciones para el uso del _locale_ en el sitio, y que los usuarios puedan ver las distintas secciones con los textos adecuados.
1. Forzar a que todas las urls incluyan el parámetro `locale` y utilizar el valor por defecto para el homepage. Ejemplo:
   - `/es`
   - `/en`
   - `/es/cfp`
2. Guardar el idioma del usuario en session. La desventaja de esto es que cuando se pierda la sesión, el usuario va a tener que volver a cargar el idioma.

Personalmente voy por la 1. Uds?

**Comment by AV4TAr** [comment]
me gusta la opción 1

**Comment by AV4TAr** [comment]
@Tombar dice que 1 también. El tipo no usa github parece.
