### ISSUE TITLE
El mensaje de error del formulario de inscripción esta en inglés.

### ISSUE THREAD

**Issue by AV4TAr** [PHPmvd/phpday-website#3]
![image](https://cloud.githubusercontent.com/assets/281805/7369373/0af0bfca-ed88-11e4-84b2-104b42b156e5.png)

**Comment by iambrosi** [comment]
Ese mensaje y su contenido es mostrado por el navegador. Asumo que tu Chrome está en inglés y por eso se muestra en ese idioma.
Una solución es inhabilitar la validación de HTML5 para ese formulario y hacerlo nosotros mismos en el submit.

**Comment by AV4TAr** [comment]
Esta perfecto entonces
