### ISSUE TITLE
Problemas para borrar el cache del sitio

### ISSUE THREAD

**Issue by iambrosi** [PHPmvd/phpday-website#7]
El usuario _webpage_, propietario del código en el servidor, no puede borrar el cache (en `~webpage/phpday-website/var/cache`), ya que es generado por el usuario de apache.

**Opciones:**
1. Configurar **ACL** en el servidor y permisos para los usuario _webpage_ y _www-data_ en el directorio `~webpage/phpday-website/var/cache`
2. Hacer que el servidor web se ejecute con el usuario _webpage_
3. Agregar `umask(0000)` al código

El orden de los items ^ también corresponde a mi preferencia personal :smile: 

ping @Tombar

**Comment by Tombar** [comment]
Quedo el ACL configurado.

root@phpday:/home/webpage/phpday-website/var/cache# setfacl -Rm u:webpage:rwX .
root@phpday:/home/webpage/phpday-website/var/cache# su webpage
webpage@phpday:~/phpday-website$ git clean -fdx var funciona bien
